name: GatOS CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'targets/**'
      - 'Makefile'
      - 'setup.sh'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'targets/**'
      - 'Makefile'
      - 'setup.sh'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt update
        chmod +x setup.sh
        ./setup.sh

    - name: Build GatOS
      run: |
        make clean
        make

    - name: Find ISO file
      id: find_iso
      run: |
        ISO_PATH=$(find dist/x86_64 -maxdepth 1 -type f -name "GatOS-*.iso" | sort -r | head -n1)
        if [ -z "$ISO_PATH" ]; then
          echo "No ISO file found in dist/x86_64"
          exit 1
        fi
        echo "Found ISO: $ISO_PATH"
        echo "iso_path=$ISO_PATH" >> $GITHUB_OUTPUT

    - name: Run Kernel in QEMU
      run: |
        timeout 10s qemu-system-x86_64 \
          -cdrom "${{ steps.find_iso.outputs.iso_path }}" \
          -nographic \
          -serial file:serial.log \
          -no-reboot || true

    - name: Parse Serial Output and Validate Tests
      run: |
        if ! grep -q "\[[0-9]\+/[0-9]\+\]" serial.log; then
          echo "No test output found"
          echo "Serial log:"
          cat serial.log || true
          exit 1
        fi

        total=$(grep -o '\[[0-9]\+/[0-9]\+\]' serial.log | tail -n1 | sed 's/.*\/\([0-9]\+\)].*/\1/')
        passed=$(grep -o '\[[0-9]\+/[0-9]\+\]' serial.log | tail -n1 | sed 's/\[\([0-9]\+\)\/.*/\1/')
        echo "Passed $passed out of $total tests"

        if [ "$passed" -ne "$total" ]; then
          echo "$((total - passed)) tests failed"
          echo "Serial log:"
          cat serial.log
          exit 1
        fi

    - name: Upload Serial Log (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: serial-log
        path: serial.log
